name: collaborative design
favicon: null
layout_spectrum: 1
typography_spectrum: 0.7720439166296273
title: code
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#dad8ed'
    - '#4a4a70'
    - '#aeabc0'
  brandStrength: 0.125
  lightness: 0.7315305415540934
  saturation: 0.5931777262594551
  rhythmicContrast: 0.75
purpose: []
