name: bhaumik modi
favicon: null
layout_spectrum: 0.32056
typography_spectrum: 0.37888
title: collaborative design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a5a8a1'
    - '#2f2c27'
    - '#000000'
    - '#5a584b'
  brandStrength: 0.1875
  lightness: 0.625
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
