analytics: {}
color:
  brandColors:
    - '#000000'
    - '#0F1417'
    - '#040809'
    - '#1D2528'
    - '#2B3336'
  brandStrength: 0.1875
  lightness: 0.625
  rhythmicContrast: 0
  saturation: 0.5625
cta: {}
layout_spectrum: 0.404279
name: bhaumik modi
opengraph: {}
purpose: []
typography_spectrum: 0.37888
